# Generated by Django 4.0.2 on 2022-02-19 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='applyhere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailid', models.TextField(null=True)),
                ('profile', models.TextField(null=True)),
                ('linkedin', models.TextField(null=True)),
                ('ceo', models.TextField(null=True)),
                ('startup', models.TextField(null=True)),
                ('weblink', models.TextField(null=True)),
                ('estdate', models.TextField(null=True)),
                ('targetmarket', models.TextField(null=True)),
                ('targetsize', models.TextField(null=True)),
                ('funding', models.TextField(null=True)),
                ('investors', models.TextField(null=True)),
                ('monthrevenue1', models.TextField(null=True)),
                ('monthrevenue2', models.TextField(null=True)),
                ('monthrevenue3', models.TextField(null=True)),
                ('presentation', models.TextField(null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='form',
        ),
    ]
